### ISSUE TITLE
Logic bug in drawNode()

### ISSUE THREAD

**Issue by isakvi** [eastlin7/TreeVisualizer#11]
Right now, the program is crashing because of faulty logic in above mentioned method in the Tree class. I'm currently reworking this method

**Comment by eastlin7** [comment]
Alright great :)

Den 4 maj 2017 10:31 skrev "isakvi" <notifications@github.com>:

**Comment by isakvi** [comment]
Faulty logic corrected. The program is no longer crashing and is working as intended (at this stage of development)
