### ISSUE TITLE
Log for user

### ISSUE THREAD

**Issue by isakvi** [eastlin7/TreeVisualizer#14]
It would be good to implement a log for the user. It should be a big text box containing information such as:
*Inserted string "blablabla"
*Cleared tree

Obviously it should be updated every time an action is done by the user

**Comment by isakvi** [comment]
The log now handles user string inputs and clear button usage.
I'll leave this issue open in case the log will be dealt more tasks

**Comment by isakvi** [comment]
Updated the class to handle long strings by shortening them

**Comment by isakvi** [comment]
Sometimes the log feels a little cluttered and it becomes hard separating entries from eachother. Could we have each entry in the log begin with a symbol of sorts? This would make it easier to see if a line in the log is a continuation of the last line, or a new entry. An example:

**This entry is supposed to be very long, but I  don't have something to
write about. The weather is nice today though.
My new entry starts here and is not very informational.**

Would instead be:

**+This entry is supposed to be very long, but I  don't have something to
write about. The weather is nice today though.
+My new entry starts here and is not very informational.**

Of course, the symbol '+' can be something else.

**Comment by eastlin7** [comment]
i'm on it :+1:

**Comment by eastlin7** [comment]
Done!
