### ISSUE TITLE
Tree generator button

### ISSUE THREAD

**Issue by isakvi** [eastlin7/TreeVisualizer#16]
To rapidly create big trees, we should have a button to generate trees of desired size with random(?) strings

**Comment by isakvi** [comment]
It's now working correctly in the newly created branch. Thinking of renaming the button to "Add nodes" since a better function of the button would be to add nodes to the current tree, rather than redraw a tree from scratch.

If a user wanted to have a tree of a specific size, they could just use the "Clear button" before using "Add node."

**Comment by eastlin7** [comment]
That would be a more fitting label indeed :+1:

**Comment by eastlin7** [comment]
Should probably merge it into main soon

**Comment by isakvi** [comment]
The button is now fully implemented.
