### ISSUE TITLE
Tree Node class (Circle)

### ISSUE THREAD

**Issue by eastlin7** [eastlin7/TreeVisualizer#2]
Our "Ball" class which gets stored in the tree & visualized on the display

Variables
* Position (X & Y) 
* Diameter (Needs to be a global variable) 
* Parent

**Comment by isakvi** [comment]
So far, our tree node is represented by the Circle class in the repo.
It isn't used by any of the other classes yet and can thus be modified without disturbing other classes

**Comment by eastlin7** [comment]
Updated title to be more clear

**Comment by isakvi** [comment]
At the moment it seems redundant to represent the nodes as instances of a class, since NodeVisualizer will probably redraw the entire tree each time the tree is updated

**Comment by eastlin7** [comment]
agreed we'll keep the issue up until it's decided

**Comment by isakvi** [comment]
We have decided to not represent the nodes as instances of a class
