### ISSUE TITLE
Migrating the updateCounters() method

### ISSUE THREAD

**Issue by isakvi** [eastlin7/TreeVisualizer#25]
Since GenerateTreeButton  needs to access this method it must be placed in another class since we cannot reference an instance of Graphics for use of the method.

**Comment by isakvi** [comment]
My idea as of now: only Graphics and GenerateTreeButton needs the method, but GenerateTreeButton cannot reference an instance of Graphics. Vice versa works, and thus it seems logical to migrate the updateCounters() method to the GenerateTreeButton class.

**Comment by isakvi** [comment]
It's done, the counters now update when you use the "Add nodes"-button

**Comment by eastlin7** [comment]
Great! Now I believe we sorted all the easily fixed problems
