### ISSUE TITLE
Node Visualizer class 

### ISSUE THREAD

**Issue by eastlin7** [eastlin7/TreeVisualizer#7]
This class handles the visualizing of each node from the tree starting at root.

* Position
* Size

Pseudocode:  Paint ball method

`Paint ball method`
`   Visualize node as a circle `
`   Diameter = X `
`   Diameter = Position Y `
` If Left or Right exist {`
`  -  Do Recursive Call Paint Ball method Left or Right }`

**Comment by isakvi** [comment]
The Visualizer class needs to know about the instance of Graphics. 
Graphics extends Application, I'll research how you reference to an instance of a subclass of Application

**Comment by isakvi** [comment]
I reworked the idea of the Visualizer class into the NodeVisualizer, it only needs a reference to the canvas used i Graphics class

**Comment by eastlin7** [comment]
Sweet :+1:

**Comment by isakvi** [comment]
The recursive painting of nodes has been delegated to the Tree class. Right now the NodeVisualizer only paints a single node when the Tree class says it should.

**Comment by eastlin7** [comment]
I'll close this issue, we can discuss later if we want to make an issue for resizing/changing positioning of the tree nodes on demand. 

So far I'm sceptical that we'll have a good solution to it within our timeframe
